#!/bin/bash
if [[ "$#" -eq 2 ]]
then

# make project dir structure
 GROUPID=$( echo "$2" | tr '.' '/' )
 ARTIFACTID="$1"
 mkdir -p ~/Kod/$ARTIFACTID/src/{main,test}/{java,resources}/$GROUPID

# initialize git repo
 git init ~/Kod/$ARTIFACTID

# change dir to project dir
 cd ~/Kod/$ARTIFACTID

# download .gitignore from gitignore.io
 wget "https://gitignore.io/api/java,maven,intellij+all" -O ".gitignore"

# create README.md
 echo -e "# About $ARTIFACTID\n## Prerequisites\n## Running\n## What to review?\n" > README.md

# create estymaty.md
# uncomment to use
# echo -e "# Nazwa projektu\n\n|Data  |Pesymistyczna|Realistyczna|Optymistyczna|\n:-------------------:|:-------------------:|:-------------------|-------------------:\n|data|opis pesymistyczny|opis realistyczny|opis optymistyczny" > estymaty.md

# download POM.xml from gist.github.com
# update url after each change of gist
 wget "https://gist.githubusercontent.com/marcinogo/5e68afb858f5fc5c8e599f98ecb1cf89/raw/6f24eb8ad77a74b05850633675b34b1e009f2567/pom.xml"

# replace groupID and artifactID in pom.xml
 sed -i "s/#GROUPID/$GRUPID/g" ~+/pom.xml
 sed -i "s/#ARTIFACTID/$ARTIFACTID/g" ~+/pom.xml
 sed -i "s/#APP_NAME/$ARTIFACTID/g" ~+/pom.xml

# open intellij community edition (snap) with this project in background
 intellij-idea-community pom.xml &

# create initial commit
 git add .
 git commit -m "Initial commit"
 
else
 echo "You have enter exactly 2 args at startup: ARTIFACTID and GROUPID"
fi
